name: Android Stable Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties

      - name: Build stable debug
        run: ./gradlew :smarttubetv:assembleStstableDebug -x lint -x test --no-daemon

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: smarttubetv-ststable-debug-apks
          path: smarttubetv/build/outputs/apk/ststable/debug/**/*.apk

