name: Android Stable Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK 17 for Android SDK tools
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Set up Android SDK (cmdline-tools requires JDK 17)
        uses: android-actions/setup-android@v3

      - name: Accept licenses and install SDK packages
        shell: bash
        run: |
          set -euxo pipefail
          SDKMANAGER="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"
          if [ ! -x "$SDKMANAGER" ]; then
            # Fallback in case 'latest' is not present
            SDKMANAGER=$(echo "$ANDROID_SDK_ROOT"/cmdline-tools/*/bin/sdkmanager | head -n1)
          fi
          yes | "$SDKMANAGER" --sdk_root="$ANDROID_SDK_ROOT" --licenses
          "$SDKMANAGER" --sdk_root="$ANDROID_SDK_ROOT" --install \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;30.0.3"

      - name: Switch to JDK 11 for Gradle/AGP 4.x
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties

      - name: Build stable debug
        run: ./gradlew :smarttubetv:assembleStstableDebug -x lint -x test --no-daemon

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: smarttubetv-ststable-debug-apks
          path: smarttubetv/build/outputs/apk/ststable/debug/**/*.apk

